# -*- coding: utf-8 -*-
"""Copy of session-2-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ft0KvFAlxN6XhiV37nAnuH2VdZThh3fA

### `Problem 1`: Write a program that will give you in hand monthly salary after deduction on CTC - HRA(10%), DA(5%), PF(3%) and taxes deduction as below:

> Salary(Lakhs) : Tax(%)

*   Below 5 : 0%
*   5-10 : 10%
*   10-20 : 20%
*   aboove 20 : 30%
"""

CTC = float(input('Enter your CTC: '))
HRA = 0.1*CTC
DA = 0.05*CTC
PF = 0.03*CTC
Salary = CTC-HRA-DA-PF

if Salary < 500000:
  print(Salary)
elif Salary>=500000 and Salary <=1000000:
  print(Salary-0.1*Salary)
elif Salary>100000 and Salary <=2000000:
  print(Salary-0.2*Salary)
else:
  print(Salary-0.3*Salary)

"""### `Problem 2`: Write a program that take a user input of three angles and will find out whether it can form a triangle or not."""

a = int(input('Enter the first side: '))
b = int(input('Enter the second side: '))
c = int(input('Enter the third side: '))

if a+b+c==180:
  print('Can form a Triangle')
else:
  print("Can't form a Triangle")

"""### `Problem 3`: Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit."""

cost_price = float(input('Enter the cost price: '))
selling_price = float(input('Enter the selling price: '))

if selling_price > cost_price:
  print("It's a profit!!!.....Keep it up")
else:
  print("It's a loss damnit!")

"""### `Problem 4`: Write a menu-driven program -
1. cm to ft
2. km to miles
3. USD to INR
4. exit
"""

menu = int(input("""
Hello! How're you doing today? Please select one:-
Enter '1' for cm to ft conversion:
Enter '2' for km to miles conversion:
Enter '3' for currency conversion(USD to INR):
Enter '4' to exit:
"""))

if menu == 1:
  a = float(input('Enter in cm: '))
  conv1 = a*0.0328
  print(conv1)
  print('Thank you for using our services:-)')
elif menu == 2:
  b = float(input('Enter in km: '))
  conv2 = b*0.62137
  print(conv2)

elif menu == 3:
  c = float(input('Enter currency in USD: '))
  conv3 = c*84.2
  print(conv3)
elif menu == 4 :
  print('''Your'e exited''')

"""### `Problem 5` - Exercise 12: Display Fibonacci series up to 10 terms.

*Note: The Fibonacci Sequence is a series of numbers. The next number is found by adding up the two numbers before it. The first two numbers are 0 and 1. For example, 0, 1, 1, 2, 3, 5, 8, 13, 21. The next number in this series above is 13+21 = 34*
"""

n = int(input('Enter the n terms: '))
f1 = 0
f2 = 1
fn = 0
for i in range(n):
  print(fn)
  f1 = f2
  f2 = fn
  fn = f1+f2

"""### `Problem 6` - Find the factorial of a given number.

Write a program to use the loop to find the factorial of a given number.

The factorial (symbol: `!`) means to multiply all whole numbers from the chosen number down to 1.

For example: calculate the factorial of 5

```bash
5! = 5 × 4 × 3 × 2 × 1 = 120
```

Output:

```bash
120
```
"""

n = int(input('Enter a number: '))
fact = 1
for i in range(1, n+1):
  fact = fact * i
  if i!=n:
    continue
  print(fact)

"""### `Problem 7` - Reverse a given integer number.

Example:

`Input:`

```bash
76542
```

`Output:`

```bash
24567
```
"""

num = input('Enter an integer: ')
print(num[::-1])

"""### `Problem 8`: Take a user input as integer N. Find out the sum from 1 to N. If any number if divisible by 5, then skip that number. And if the sum is greater than 300, don't need to calculate the sum further more. Print the final result. And don't use for loop to solve this problem.

**Example 1:**

`Input:`

```bash
30
```

`Output:`

```bash
276
```
"""

n = int(input('Enter an Integer: '))
sum=0
num=1
while num<=n:
  if num%5!=0:
    sum+=num
  elif num>=300:
    break
  num+=1
print(sum)

"""### `Problem 9`: Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers."""

sum = 0
count = 0

while True:
  n = int(input('Enter a number: '))
  sum = sum+n
  count = count+1
  if n==0:
    count = count-1
    print('''The toltal sum of numbers you've entered is: ''' , sum)
    average = sum/count
    print('''Average is: ''', average)
    break
  else:
    print(n)

"""###`Problem 9`: Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line."""

for i in range(2000, 3201):
  if i%7 == 0 and i%5 != 0:
    print(i, end=',')

"""###`Problem 10`: Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a space-separated sequence on a single line.


"""

for i in range(1000, 3001):
  Str_num = str(i)
  if all(int(digit)%2==0 for digit in Str_num):
    print(i, end=' ')

"""###`Problem 11`: A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps.
The trace of robot movement is shown as the following:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
> The numbers after the direction are steps.

> `!` means robot stop there.

**Please write a program to compute the distance from current position after a sequence of movement and original point.**

*If the distance is a float, then just print the nearest integer.*

Example:

`Input`:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
`Output`:
```
2
```
"""

import math

pos = [0,0]

while True:
  p = input('Enter the robot position: ')
  if not p:
    break
  movement = p.split(' ')
  direction = movement[0]
  steps = int(movement[1])
  if direction=='up':
    pos[0]=pos[1]+steps
  elif direction=='down':
    pos[0]-=steps
  elif direction=='left':
    pos[1]-=steps
  elif direction=='right':
    pos[1]+=steps
  else:
    pass
print(int(math.floor(math.sqrt(pos[1]**2+pos[0]**2))))

"""###`Problem 12`:Write a program to print whether a given number is a prime number or not"""

n = int(input('Enter a number: '))
if n <= 1:
  print(n, 'is not a prime number')
else:
  for i in range(2,n):
    if n%i==0:
      print(n,'is not a prime number')
      break
  else:
    print(n, 'is a prime number')

"""###`Problem 13`:Print all the Armstrong numbers in a given range.
Range will be provided by the user<br>
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.
"""

n = int(input('enter a range: '))
for i in range(n+1):
  i_str = str(i)
  if sum((int(digit)**3 for digit in i_str))==i:
    print(i)

"""###`Problem 14`:Calculate the angle between the hour hand and minute hand.

Note: There can be two angles between hands; we need to print a minimum of two. Also, we need to print the floor of the final result angle. For example, if the final angle is 10.61, we need to print 10.

Input:<br>
H = 9 , M = 0<br>
Output:<br>
90<br>
Explanation:<br>
The minimum angle between hour and minute
hand when the time is 9 is 90 degress.
"""

import math
H = int(input('Enter Hour: '))
M = int(input('Enter Minute: '))
H_angle = 30*H+0.5*M
M_angle = 6*M
angle1 = H_angle-M_angle
angle2 = 360-angle1
angle = min(angle1, angle2)
print(math.floor(angle),'degrees')

"""###`Problem 15`:Given two rectangles, find if the given two rectangles overlap or not. A rectangle is denoted by providing the x and y coordinates of two points: the left top corner and the right bottom corner of the rectangle. Two rectangles sharing a side are considered overlapping. (L1 and R1 are the extreme points of the first rectangle and L2 and R2 are the extreme points of the second rectangle).

Note: It may be assumed that the rectangles are parallel to the coordinate axis.

<img src='https://www.geeksforgeeks.org/wp-content/uploads/rectanglesOverlap.png' width='300' height='200'>
"""

l1_x = int(input('Enter L1_x co-ordinate: '))
l1_y = int(input('Enter L1_y co-ordinate: '))
R1_x = int(input('Enter R1_x co-ordinate: '))
R1_y = int(input('Enter R1_y co-ordinate: '))
l2_x = int(input('Enter L2_x co-ordinate: '))
l2_y = int(input('Enter L2_y co-ordinate: '))
R2_x = int(input('Enter R2_x co-ordinate: '))
R2_y = int(input('Enter R2_y co-ordinate: '))

if l1_x > R2_x or l2_x > R1_y:
  print('Cannot Overlap')
elif R1_y > l1_y or R1_y > l2_y:
  print('cannot overlap')
else:
  print('Rectangle overlaps eachother')