# -*- coding: utf-8 -*-
"""Copy of session-5-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6pujrlTKHVTVtbSx6nQ3kTRcvgnkx1M

# Tuple

###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem in which we need to perform concatenation of records from the similarity of initial element. This problem can have applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
Output : [(5, 6, 7, 8), (6, 10), (7, 13)]
```
"""

test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]

l= []
while test_list:

  temp_tup = test_list[0]
  group = [temp_tup]

  for i in test_list[1:]:
    if temp_tup[0] == i[0]:
      group.append(i)

  merged_group = (group[0][0], *[j for i in group for j in i[1:]])
  l.append(merged_group)

  test_list = [i for i in test_list if i[0]!=temp_tup[0]]


l

"""###`Q2:` Multiply Adjacent elements (both side) and take sum of right and lest side multiplication result.


For eg.
```
The original tuple : (1, 5, 7, 8, 10)
Resultant tuple after multiplication :

(1*5, 1*5+5*7, 7*5 + 7*8, 8*7 + 8*10, 10*8) -> (5, 40, 91, 136, 80)

output-(5, 40, 91, 136, 80)
```
"""

t = (1, 5, 7, 8, 10)

r = []

for i in range(len(t)):
    if i==0:
        a=t[i]*t[i+1]
    elif i==len(t)-1:
        a=t[i]*t[i-1]
    else:
        a=t[i]*t[i-1]+t[i]*t[i+1]
        i+=1
    r.append(a)

tuple(r)

"""###`Q3`: Check is tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```
"""

t1 = (1,2,3,0)
t2 = (1,2,3,4)

length = min(len(t1),len(t2))

for i in range(length):
  if t1[i] != t2[i]:
    print('t1 and t2 are not same')

"""###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```
"""

list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

L_count = 0
S_count = 0
T_count = 0

for i in list1:
  if type(i) is list:
    L_count+=1
  elif type(i) is set:
    S_count+=1
  else:
    T_count+=1

print("List"+'-',L_count)
print("Tuple"+'-',T_count)
print("Set"+'-',S_count)

"""###`Q5`: Shortlist Students for a Job role
Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

Show every students record in form of tuples if matches all required criteria.

It is assumed that there will be only one primry skill.

If no such candidate found, print `No such candidate`

`Input:`
```
Enter No of records- 2
Enter Details of student-1
Enter Student name- Manohar
Enter Higher Education- B.Tech
Enter Primary Skill- Python
Enter Year of Graduation- 2022
Enter Details of student-2
Enter Student name- Ponian
Enter Higher Education- B.Sc.
Enter Primary Skill- C++
Enter Year of Graduation- 2020

Enter Job Role Requirement
Enter Skill- Python
Enter Higher Education- B.Tech
Enter Year of Graduation- 2022
```

`Output`
```
('Manohar', 'B.tech', 'Python', '2022')
```

"""

a = int(input("Enter no. of Students applied for Job: "))

l = []
for i in range(1, a+1):
  print(f"Enter details of student-{i} ")
  name = input("Enter Student name- ")
  edu = input("Enter Higher Education- ")
  skill = input("Enter Primary Skill- ")
  grad_year = input("Enter Year of Graduation- ")
  print("                            ")
  l.append([name, edu, skill, grad_year])



print("Enter Job Role Requirements")
req_skill = input("Enter Skill- ")
req_edu = input("Enter Higher education- ")
req_grad = input("Enter Year of Graduation- ")
print("                                  ")

matches = 0
for i in range(len(l)):
  if l[i][1] == req_edu and  l[i][2] == req_skill and l[i][3] == req_grad:
    print(tuple(l[i]))
    matches+=1

if matches==0:
  print("no match found")

"""gff# Set

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```
"""

ar1 = set([1, 5, 10, 20, 40, 80])
ar2 = set([6, 7, 20, 80, 100])
ar3 = set([3, 4, 15, 20, 30, 70, 80, 120])

ar1 & ar2 & ar3

"""###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```
"""

Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"

Str1 = set(Str1)

vowels = {'a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'}

print("No of unique vowels-",len(Str1 & vowels))

"""### `Q3:` Write a program to Check if a given string is binary string of or not.

A string is said to be binary if it's consists of only two unique characters.

Take string input from user.

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```
"""

a = input("Enter the binary str: ")

a = set(a)
if len(a) == 2:
  print("yes")
else:
  print("no")

"""### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```
"""

a = [[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]

list(set([j for i in a for j in i]))

"""### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```
"""

lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}

[i for i in lst1 for j in lst2 if i==j]

"""# Dictionary

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```
"""

test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}

a = {i:len(set(j)) for i,j in test_dict.items()}

max(a, key=a.get)

"""### `Q2`: Replace words from Dictionary. Given String, replace it’s words from lookup dictionary.

**Example 1:**

Input:

```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
```

Output:

```bash
CampusX is the best channel for Data-Science students.
```

**Example 2:**

Input:
```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"good" : "is the best channel", "ds" : "Data-Science"}
```

Output:
```bash
CampusX best for DS students.
```
"""

test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}

for i, j in repl_dict.items():
  test_str= test_str.replace(i,j)
test_str

"""### `Q3`: Convert List to List of dictionaries. Given list values and keys list, convert these values to key value pairs in form of list of dictionaries.

**Example 1:**

Input:
```bash
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]
```

**Example 2:**

Input:
```bash
test_list = ["CampusX", 10]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'CampusX', 'id': 10}]
```
"""

test_list = ["CampusX", 10]
key_list = ["name", "id"]

[{key_list[i]:test_list[i]} for i in range(len(test_list))]

"""### `Q4`: Convert a list of Tuples into Dictionary.

**Example 1:**

Input:
```bash
[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
```

Output:
```bash
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
```

**Example 2:**

Input:
```bash
[('A', 1), ('B', 2), ('C', 3)]
```

Output:
```bash
{'A': [1], 'B': [2], 'C': [3]}
```
"""

l = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]

{i:[j] for i,j in l}

"""### `Q5`: Sort Dictionary key and values List.

**Example 1:**

Input:

```bash
{'c': [3], 'b': [12, 10], 'a': [19, 4]}
```

Output:

```bash
{'a': [4, 19], 'b': [10, 12], 'c': [3]}
```

**Example 2:**

Input:

```bash
{'c': [10, 34, 3]}
```

Output:

```bash
{'c': [3, 10, 34]}
```
"""

ilist = {'c': [3], 'b': [12, 10], 'a': [19, 4]}

{i:j for i,j in sorted(ilist.items())}

